<?php

return array (
  'ShowMessageValidateListener' => 'E:\\phpWork\\lucklybet\\modules/\\ShowMessageValidateListener.class.php',
  'WebLifeListener' => 'E:\\phpWork\\lucklybet\\modules/\\WebLifeListener.class.php',
  '.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/\\ShowMessageValidateListener.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/\\WebLifeListener.class.php',
  ),
  'admin.actions.AbstractAdminAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\AbstractAdminAction.class.php',
  'AbstractAdminAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\AbstractAdminAction.class.php',
  'admin.actions.ConfigAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\ConfigAction.class.php',
  'ConfigAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\ConfigAction.class.php',
  'admin.actions.CustomTypeAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\CustomTypeAction.class.php',
  'CustomTypeAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\CustomTypeAction.class.php',
  'admin.actions.EmailTemplateAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\EmailTemplateAction.class.php',
  'EmailTemplateAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\EmailTemplateAction.class.php',
  'admin.actions.ExchangeAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\ExchangeAction.class.php',
  'ExchangeAction' => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\ExchangeAction.class.php',
  'admin.actions.GoodsAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\GoodsAction.class.php',
  'GoodsAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\GoodsAction.class.php',
  'admin.actions.GuessAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\GuessAction.class.php',
  'GuessAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\GuessAction.class.php',
  'admin.actions.GuessCategoryAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\GuessCategoryAction.class.php',
  'GuessCategoryAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\GuessCategoryAction.class.php',
  'admin.actions.GuessPointAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\GuessPointAction.class.php',
  'GuessPointAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\GuessPointAction.class.php',
  'admin.actions.IndexAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\IndexAction.class.php',
  'IndexAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\IndexAction.class.php',
  'admin.actions.LoginAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\LoginAction.class.php',
  'LoginAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\LoginAction.class.php',
  'admin.actions.LogoutAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\LogoutAction.class.php',
  'LogoutAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\LogoutAction.class.php',
  'admin.actions.MakersAuthAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\MakersAuthAction.class.php',
  'MakersAuthAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\MakersAuthAction.class.php',
  'admin.actions.ManageGroupAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\ManageGroupAction.class.php',
  'ManageGroupAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\ManageGroupAction.class.php',
  'admin.actions.ManagerAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\ManagerAction.class.php',
  'ManagerAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\ManagerAction.class.php',
  'admin.actions.MenuAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\MenuAction.class.php',
  'MenuAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\MenuAction.class.php',
  'admin.actions.MessageAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\MessageAction.class.php',
  'MessageAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\MessageAction.class.php',
  'admin.actions.NewsAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\NewsAction.class.php',
  'NewsAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\NewsAction.class.php',
  'admin.actions.NewsCategoryAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\NewsCategoryAction.class.php',
  'NewsCategoryAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\NewsCategoryAction.class.php',
  'admin.actions.PasswordAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\PasswordAction.class.php',
  'PasswordAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\PasswordAction.class.php',
  'admin.actions.PlayWayAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\PlayWayAction.class.php',
  'PlayWayAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\PlayWayAction.class.php',
  'admin.actions.RechargeAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\RechargeAction.class.php',
  'RechargeAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\RechargeAction.class.php',
  'admin.actions.RegionAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\RegionAction.class.php',
  'RegionAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\RegionAction.class.php',
  'admin.actions.UserAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\UserAction.class.php',
  'UserAction' => 'E:\\phpWork\\lucklybet\\modules/ajax\\actions\\UserAction.class.php',
  'admin.actions.WeiboAction' => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\WeiboAction.class.php',
  'WeiboAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\WeiboAction.class.php',
  'admin.actions.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\AbstractAdminAction.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\ConfigAction.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\CustomTypeAction.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\EmailTemplateAction.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\ExchangeAction.class.php',
    5 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\GoodsAction.class.php',
    6 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\GuessAction.class.php',
    7 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\GuessCategoryAction.class.php',
    8 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\GuessPointAction.class.php',
    9 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\IndexAction.class.php',
    10 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\LoginAction.class.php',
    11 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\LogoutAction.class.php',
    12 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\MakersAuthAction.class.php',
    13 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\ManageGroupAction.class.php',
    14 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\ManagerAction.class.php',
    15 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\MenuAction.class.php',
    16 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\MessageAction.class.php',
    17 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\NewsAction.class.php',
    18 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\NewsCategoryAction.class.php',
    19 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\PasswordAction.class.php',
    20 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\PlayWayAction.class.php',
    21 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\RechargeAction.class.php',
    22 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\RegionAction.class.php',
    23 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\UserAction.class.php',
    24 => 'E:\\phpWork\\lucklybet\\modules/admin\\actions\\WeiboAction.class.php',
  ),
  'admin.listeners.AdminOpPermissionFilter' => 'E:\\phpWork\\lucklybet\\modules/admin\\listeners\\AdminOpPermissionFilter.class.php',
  'AdminOpPermissionFilter' => 'E:\\phpWork\\lucklybet\\modules/admin\\listeners\\AdminOpPermissionFilter.class.php',
  'admin.listeners.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/admin\\listeners\\AdminOpPermissionFilter.class.php',
  ),
  'admin.model.ManageGroup' => 'E:\\phpWork\\lucklybet\\modules/admin\\model\\ManageGroup.class.php',
  'ManageGroup' => 'E:\\phpWork\\lucklybet\\modules/admin\\model\\ManageGroup.class.php',
  'admin.model.Manager' => 'E:\\phpWork\\lucklybet\\modules/admin\\model\\Manager.class.php',
  'Manager' => 'E:\\phpWork\\lucklybet\\modules/admin\\model\\Manager.class.php',
  'admin.model.Menu' => 'E:\\phpWork\\lucklybet\\modules/admin\\model\\Menu.class.php',
  'Menu' => 'E:\\phpWork\\lucklybet\\modules/admin\\model\\Menu.class.php',
  'admin.model.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/admin\\model\\ManageGroup.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/admin\\model\\Manager.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/admin\\model\\Menu.class.php',
  ),
  'admin.service.AdminOperationService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\AdminOperationService.class.php',
  'AdminOperationService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\AdminOperationService.class.php',
  'admin.service.AdminServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\AdminServiceFactory.class.php',
  'AdminServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\AdminServiceFactory.class.php',
  'admin.service.ManagerService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\ManagerService.class.php',
  'ManagerService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\ManagerService.class.php',
  'admin.service.MenuService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\MenuService.class.php',
  'MenuService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\MenuService.class.php',
  'admin.service.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\AdminOperationService.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\AdminServiceFactory.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\ManagerService.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\MenuService.class.php',
  ),
  'admin.service.cache.CacheMenuService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\cache\\CacheMenuService.class.php',
  'CacheMenuService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\cache\\CacheMenuService.class.php',
  'admin.service.cache.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\cache\\CacheMenuService.class.php',
  ),
  'admin.service.interface.IAdminOperationService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\interface\\IAdminOperationService.class.php',
  'IAdminOperationService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\interface\\IAdminOperationService.class.php',
  'admin.service.interface.IManagerService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\interface\\IManagerService.class.php',
  'IManagerService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\interface\\IManagerService.class.php',
  'admin.service.interface.IMenuService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\interface\\IMenuService.class.php',
  'IMenuService' => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\interface\\IMenuService.class.php',
  'admin.service.interface.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\interface\\IAdminOperationService.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\interface\\IManagerService.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/admin\\service\\interface\\IMenuService.class.php',
  ),
  'ajax.actions.CronAction' => 'E:\\phpWork\\lucklybet\\modules/ajax\\actions\\CronAction.class.php',
  'CronAction' => 'E:\\phpWork\\lucklybet\\modules/ajax\\actions\\CronAction.class.php',
  'ajax.actions.UserAction' => 'E:\\phpWork\\lucklybet\\modules/ajax\\actions\\UserAction.class.php',
  'ajax.actions.VerifyAction' => 'E:\\phpWork\\lucklybet\\modules/ajax\\actions\\VerifyAction.class.php',
  'VerifyAction' => 'E:\\phpWork\\lucklybet\\modules/ajax\\actions\\VerifyAction.class.php',
  'ajax.actions.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/ajax\\actions\\CronAction.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/ajax\\actions\\UserAction.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/ajax\\actions\\VerifyAction.class.php',
  ),
  'ajax.model.AddressMultiaddrs' => 'E:\\phpWork\\lucklybet\\modules/ajax\\model\\AddressMultiaddrs.class.php',
  'AddressMultiaddrs' => 'E:\\phpWork\\lucklybet\\modules/ajax\\model\\AddressMultiaddrs.class.php',
  'ajax.model.AjaxResult' => 'E:\\phpWork\\lucklybet\\modules/ajax\\model\\AjaxResult.class.php',
  'AjaxResult' => 'E:\\phpWork\\lucklybet\\modules/ajax\\model\\AjaxResult.class.php',
  'ajax.model.UserDeposit' => 'E:\\phpWork\\lucklybet\\modules/ajax\\model\\UserDeposit.class.php',
  'UserDeposit' => 'E:\\phpWork\\lucklybet\\modules/ajax\\model\\UserDeposit.class.php',
  'ajax.model.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/ajax\\model\\AddressMultiaddrs.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/ajax\\model\\AjaxResult.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/ajax\\model\\UserDeposit.class.php',
  ),
  'common.actions.AjaxNeedLoginAction' => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\AjaxNeedLoginAction.class.php',
  'AjaxNeedLoginAction' => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\AjaxNeedLoginAction.class.php',
  'common.actions.CommonAction' => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\CommonAction.class.php',
  'CommonAction' => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\CommonAction.class.php',
  'common.actions.IndexAction' => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\IndexAction.class.php',
  'common.actions.NeedLoginAction' => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\NeedLoginAction.class.php',
  'NeedLoginAction' => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\NeedLoginAction.class.php',
  'common.actions.TipAction' => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\TipAction.class.php',
  'TipAction' => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\TipAction.class.php',
  'common.actions.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\AjaxNeedLoginAction.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\CommonAction.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\IndexAction.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\NeedLoginAction.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/common\\actions\\TipAction.class.php',
  ),
  'common.model.Config' => 'E:\\phpWork\\lucklybet\\modules/common\\model\\Config.class.php',
  'Config' => 'E:\\phpWork\\lucklybet\\modules/common\\model\\Config.class.php',
  'common.model.EmailTemplate' => 'E:\\phpWork\\lucklybet\\modules/common\\model\\EmailTemplate.class.php',
  'EmailTemplate' => 'E:\\phpWork\\lucklybet\\modules/common\\model\\EmailTemplate.class.php',
  'common.model.Operation' => 'E:\\phpWork\\lucklybet\\modules/common\\model\\Operation.class.php',
  'Operation' => 'E:\\phpWork\\lucklybet\\modules/common\\model\\Operation.class.php',
  'common.model.Region' => 'E:\\phpWork\\lucklybet\\modules/common\\model\\Region.class.php',
  'Region' => 'E:\\phpWork\\lucklybet\\modules/common\\model\\Region.class.php',
  'common.model.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/common\\model\\Config.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/common\\model\\EmailTemplate.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/common\\model\\Operation.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/common\\model\\Region.class.php',
  ),
  'common.service.CommonServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\CommonServiceFactory.class.php',
  'CommonServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\CommonServiceFactory.class.php',
  'common.service.ConfigService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\ConfigService.class.php',
  'ConfigService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\ConfigService.class.php',
  'common.service.EmailService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\EmailService.class.php',
  'EmailService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\EmailService.class.php',
  'common.service.RegionService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\RegionService.class.php',
  'RegionService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\RegionService.class.php',
  'common.service.TransationSupport' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\TransationSupport.class.php',
  'TransationSupport' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\TransationSupport.class.php',
  'common.service.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/common\\service\\CommonServiceFactory.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/common\\service\\ConfigService.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/common\\service\\EmailService.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/common\\service\\RegionService.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/common\\service\\TransationSupport.class.php',
  ),
  'common.service.cache.CacheConfigService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\cache\\CacheConfigService.class.php',
  'CacheConfigService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\cache\\CacheConfigService.class.php',
  'common.service.cache.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/common\\service\\cache\\CacheConfigService.class.php',
  ),
  'common.service.interface.IConfigService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\interface\\IConfigService.class.php',
  'IConfigService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\interface\\IConfigService.class.php',
  'common.service.interface.IEmailService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\interface\\IEmailService.class.php',
  'IEmailService' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\interface\\IEmailService.class.php',
  'common.service.interface.IRegion' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\interface\\IRegion.class.php',
  'IRegion' => 'E:\\phpWork\\lucklybet\\modules/common\\service\\interface\\IRegion.class.php',
  'common.service.interface.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/common\\service\\interface\\IConfigService.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/common\\service\\interface\\IEmailService.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/common\\service\\interface\\IRegion.class.php',
  ),
  'goods.actions.ExchangeAction' => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\ExchangeAction.class.php',
  'goods.actions.ListAction' => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\ListAction.class.php',
  'ListAction' => 'E:\\phpWork\\lucklybet\\modules/news\\actions\\ListAction.class.php',
  'goods.actions.LotteryAction' => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\LotteryAction.class.php',
  'LotteryAction' => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\LotteryAction.class.php',
  'goods.actions.MyAction' => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\MyAction.class.php',
  'MyAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\MyAction.class.php',
  'goods.actions.ViewAction' => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\ViewAction.class.php',
  'ViewAction' => 'E:\\phpWork\\lucklybet\\modules/news\\actions\\ViewAction.class.php',
  'goods.actions.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\ExchangeAction.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\ListAction.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\LotteryAction.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\MyAction.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/goods\\actions\\ViewAction.class.php',
  ),
  'goods.model.Exchange' => 'E:\\phpWork\\lucklybet\\modules/goods\\model\\Exchange.class.php',
  'Exchange' => 'E:\\phpWork\\lucklybet\\modules/goods\\model\\Exchange.class.php',
  'goods.model.Goods' => 'E:\\phpWork\\lucklybet\\modules/goods\\model\\Goods.class.php',
  'Goods' => 'E:\\phpWork\\lucklybet\\modules/goods\\model\\Goods.class.php',
  'goods.model.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/goods\\model\\Exchange.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/goods\\model\\Goods.class.php',
  ),
  'goods.service.GoodsService' => 'E:\\phpWork\\lucklybet\\modules/goods\\service\\GoodsService.class.php',
  'GoodsService' => 'E:\\phpWork\\lucklybet\\modules/goods\\service\\GoodsService.class.php',
  'goods.service.GoodsServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/goods\\service\\GoodsServiceFactory.class.php',
  'GoodsServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/goods\\service\\GoodsServiceFactory.class.php',
  'goods.service.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/goods\\service\\GoodsService.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/goods\\service\\GoodsServiceFactory.class.php',
  ),
  'goods.service.interface.IGoodsService' => 'E:\\phpWork\\lucklybet\\modules/goods\\service\\interface\\IGoodsService.class.php',
  'IGoodsService' => 'E:\\phpWork\\lucklybet\\modules/goods\\service\\interface\\IGoodsService.class.php',
  'goods.service.interface.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/goods\\service\\interface\\IGoodsService.class.php',
  ),
  'guess.actions.AddAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\AddAction.class.php',
  'AddAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\AddAction.class.php',
  'guess.actions.AdminReviewAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\AdminReviewAction.class.php',
  'AdminReviewAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\AdminReviewAction.class.php',
  'guess.actions.CategoryAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\CategoryAction.class.php',
  'CategoryAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\CategoryAction.class.php',
  'guess.actions.DeleteAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\DeleteAction.class.php',
  'DeleteAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\DeleteAction.class.php',
  'guess.actions.FollowAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\FollowAction.class.php',
  'FollowAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\FollowAction.class.php',
  'guess.actions.GuessAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\GuessAction.class.php',
  'guess.actions.GuessPointAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\GuessPointAction.class.php',
  'guess.actions.ListAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\ListAction.class.php',
  'guess.actions.MyAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\MyAction.class.php',
  'guess.actions.PlayAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\PlayAction.class.php',
  'PlayAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\PlayAction.class.php',
  'guess.actions.RudgeAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\RudgeAction.class.php',
  'RudgeAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\RudgeAction.class.php',
  'guess.actions.ViewAction' => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\ViewAction.class.php',
  'guess.actions.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\AddAction.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\AdminReviewAction.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\CategoryAction.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\DeleteAction.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\FollowAction.class.php',
    5 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\GuessAction.class.php',
    6 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\GuessPointAction.class.php',
    7 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\ListAction.class.php',
    8 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\MyAction.class.php',
    9 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\PlayAction.class.php',
    10 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\RudgeAction.class.php',
    11 => 'E:\\phpWork\\lucklybet\\modules/guess\\actions\\ViewAction.class.php',
  ),
  'guess.model.Guess' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\Guess.class.php',
  'Guess' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\Guess.class.php',
  'guess.model.GuessCategory' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\GuessCategory.class.php',
  'GuessCategory' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\GuessCategory.class.php',
  'guess.model.GuessPoint' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\GuessPoint.class.php',
  'GuessPoint' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\GuessPoint.class.php',
  'guess.model.Play' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\Play.class.php',
  'Play' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\Play.class.php',
  'guess.model.PlayData' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayData.class.php',
  'PlayData' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayData.class.php',
  'guess.model.PlayWay' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWay.class.php',
  'PlayWay' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWay.class.php',
  'guess.model.PlayWayData' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWayData.class.php',
  'PlayWayData' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWayData.class.php',
  'guess.model.PlayWayParameter' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWayParameter.class.php',
  'PlayWayParameter' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWayParameter.class.php',
  'guess.model.PlayWayParameterOption' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWayParameterOption.class.php',
  'PlayWayParameterOption' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWayParameterOption.class.php',
  'guess.model.UserGuess' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\UserGuess.class.php',
  'UserGuess' => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\UserGuess.class.php',
  'guess.model.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\Guess.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\GuessCategory.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\GuessPoint.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\Play.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayData.class.php',
    5 => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWay.class.php',
    6 => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWayData.class.php',
    7 => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWayParameter.class.php',
    8 => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\PlayWayParameterOption.class.php',
    9 => 'E:\\phpWork\\lucklybet\\modules/guess\\model\\UserGuess.class.php',
  ),
  'guess.service.CustomGuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\CustomGuessService.class.php',
  'CustomGuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\CustomGuessService.class.php',
  'guess.service.CustomPlayService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\CustomPlayService.class.php',
  'CustomPlayService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\CustomPlayService.class.php',
  'guess.service.GuessCategoryService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\GuessCategoryService.class.php',
  'GuessCategoryService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\GuessCategoryService.class.php',
  'guess.service.GuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\GuessService.class.php',
  'GuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\GuessService.class.php',
  'guess.service.GuessServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\GuessServiceFactory.class.php',
  'GuessServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\GuessServiceFactory.class.php',
  'guess.service.PlayService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\PlayService.class.php',
  'PlayService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\PlayService.class.php',
  'guess.service.PlayWayService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\PlayWayService.class.php',
  'PlayWayService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\PlayWayService.class.php',
  'guess.service.UserGuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\UserGuessService.class.php',
  'UserGuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\UserGuessService.class.php',
  'guess.service.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\CustomGuessService.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\CustomPlayService.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\GuessCategoryService.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\GuessService.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\GuessServiceFactory.class.php',
    5 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\PlayService.class.php',
    6 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\PlayWayService.class.php',
    7 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\UserGuessService.class.php',
  ),
  'guess.service.interface.ICustomGuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\ICustomGuessService.class.php',
  'ICustomGuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\ICustomGuessService.class.php',
  'guess.service.interface.IGuessCategoryService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IGuessCategoryService.class.php',
  'IGuessCategoryService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IGuessCategoryService.class.php',
  'guess.service.interface.IGuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IGuessService.class.php',
  'IGuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IGuessService.class.php',
  'guess.service.interface.IPlayService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IPlayService.class.php',
  'IPlayService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IPlayService.class.php',
  'guess.service.interface.IPlayWayAdapter' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IPlayWayAdapter.class.php',
  'IPlayWayAdapter' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IPlayWayAdapter.class.php',
  'guess.service.interface.IPlayWayService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IPlayWayService.class.php',
  'IPlayWayService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IPlayWayService.class.php',
  'guess.service.interface.IUserGuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IUserGuessService.class.php',
  'IUserGuessService' => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IUserGuessService.class.php',
  'guess.service.interface.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\ICustomGuessService.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IGuessCategoryService.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IGuessService.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IPlayService.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IPlayWayAdapter.class.php',
    5 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IPlayWayService.class.php',
    6 => 'E:\\phpWork\\lucklybet\\modules/guess\\service\\interface\\IUserGuessService.class.php',
  ),
  'guess.utils.GuessConstant' => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\GuessConstant.class.php',
  'GuessConstant' => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\GuessConstant.class.php',
  'guess.utils.PlayWayUtil' => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\PlayWayUtil.class.php',
  'PlayWayUtil' => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\PlayWayUtil.class.php',
  'guess.utils.PlayWayValidator' => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\PlayWayValidator.class.php',
  'PlayWayValidator' => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\PlayWayValidator.class.php',
  'guess.utils.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\GuessConstant.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\PlayWayUtil.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\PlayWayValidator.class.php',
  ),
  'guess.utils.xmlparser.PlayWayXmlParser' => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\xmlparser\\PlayWayXmlParser.class.php',
  'PlayWayXmlParser' => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\xmlparser\\PlayWayXmlParser.class.php',
  'guess.utils.xmlparser.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/guess\\utils\\xmlparser\\PlayWayXmlParser.class.php',
  ),
  'member.actions.AuthAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\AuthAction.class.php',
  'AuthAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\AuthAction.class.php',
  'member.actions.BtcAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\BtcAction.class.php',
  'BtcAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\BtcAction.class.php',
  'member.actions.FollowAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\FollowAction.class.php',
  'member.actions.FriendAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\FriendAction.class.php',
  'FriendAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\FriendAction.class.php',
  'member.actions.IndexAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\IndexAction.class.php',
  'member.actions.IntegralAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\IntegralAction.class.php',
  'IntegralAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\IntegralAction.class.php',
  'member.actions.ListAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\ListAction.class.php',
  'member.actions.LoginAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\LoginAction.class.php',
  'member.actions.LogoutAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\LogoutAction.class.php',
  'member.actions.MessageAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\MessageAction.class.php',
  'member.actions.NoticeAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\NoticeAction.class.php',
  'NoticeAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\NoticeAction.class.php',
  'member.actions.PasswordAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\PasswordAction.class.php',
  'member.actions.PayAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\PayAction.class.php',
  'PayAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\PayAction.class.php',
  'member.actions.RechargeAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\RechargeAction.class.php',
  'member.actions.RegisterAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\RegisterAction.class.php',
  'RegisterAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\RegisterAction.class.php',
  'member.actions.SettingAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\SettingAction.class.php',
  'SettingAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\SettingAction.class.php',
  'member.actions.ShareAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\ShareAction.class.php',
  'ShareAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\ShareAction.class.php',
  'member.actions.SpaceAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\SpaceAction.class.php',
  'SpaceAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\SpaceAction.class.php',
  'member.actions.UploadAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\UploadAction.class.php',
  'UploadAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\UploadAction.class.php',
  'member.actions.UserCenterAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\UserCenterAction.class.php',
  'UserCenterAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\UserCenterAction.class.php',
  'member.actions.WeiboAction' => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\WeiboAction.class.php',
  'member.actions.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\AuthAction.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\BtcAction.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\FollowAction.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\FriendAction.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\IndexAction.class.php',
    5 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\IntegralAction.class.php',
    6 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\ListAction.class.php',
    7 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\LoginAction.class.php',
    8 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\LogoutAction.class.php',
    9 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\MessageAction.class.php',
    10 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\NoticeAction.class.php',
    11 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\PasswordAction.class.php',
    12 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\PayAction.class.php',
    13 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\RechargeAction.class.php',
    14 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\RegisterAction.class.php',
    15 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\SettingAction.class.php',
    16 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\ShareAction.class.php',
    17 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\SpaceAction.class.php',
    18 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\UploadAction.class.php',
    19 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\UserCenterAction.class.php',
    20 => 'E:\\phpWork\\lucklybet\\modules/member\\actions\\WeiboAction.class.php',
  ),
  'member.listeners.UserEventListener' => 'E:\\phpWork\\lucklybet\\modules/member\\listeners\\UserEventListener.class.php',
  'UserEventListener' => 'E:\\phpWork\\lucklybet\\modules/member\\listeners\\UserEventListener.class.php',
  'member.listeners.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/member\\listeners\\UserEventListener.class.php',
  ),
  'member.listeners.interface.IUserEventListener' => 'E:\\phpWork\\lucklybet\\modules/member\\listeners\\interface\\IUserEventListener.class.php',
  'IUserEventListener' => 'E:\\phpWork\\lucklybet\\modules/member\\listeners\\interface\\IUserEventListener.class.php',
  'member.listeners.interface.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/member\\listeners\\interface\\IUserEventListener.class.php',
  ),
  'member.model.Bind' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Bind.class.php',
  'Bind' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Bind.class.php',
  'member.model.Follow' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Follow.class.php',
  'Follow' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Follow.class.php',
  'member.model.Invite' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Invite.class.php',
  'Invite' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Invite.class.php',
  'member.model.Io' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Io.class.php',
  'Io' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Io.class.php',
  'member.model.Message' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Message.class.php',
  'Message' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Message.class.php',
  'member.model.Notice' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Notice.class.php',
  'Notice' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Notice.class.php',
  'member.model.Recharge' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Recharge.class.php',
  'Recharge' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Recharge.class.php',
  'member.model.Share' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Share.class.php',
  'Share' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Share.class.php',
  'member.model.User' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\User.class.php',
  'User' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\User.class.php',
  'member.model.UserWithdraw' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\UserWithdraw.class.php',
  'UserWithdraw' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\UserWithdraw.class.php',
  'member.model.Weibo' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Weibo.class.php',
  'Weibo' => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Weibo.class.php',
  'member.model.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Bind.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Follow.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Invite.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Io.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Message.class.php',
    5 => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Notice.class.php',
    6 => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Recharge.class.php',
    7 => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Share.class.php',
    8 => 'E:\\phpWork\\lucklybet\\modules/member\\model\\User.class.php',
    9 => 'E:\\phpWork\\lucklybet\\modules/member\\model\\UserWithdraw.class.php',
    10 => 'E:\\phpWork\\lucklybet\\modules/member\\model\\Weibo.class.php',
  ),
  'member.service.FollowService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\FollowService.class.php',
  'FollowService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\FollowService.class.php',
  'member.service.ImageVerificationCodeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\ImageVerificationCodeService.class.php',
  'ImageVerificationCodeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\ImageVerificationCodeService.class.php',
  'member.service.MemberServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\MemberServiceFactory.class.php',
  'MemberServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\MemberServiceFactory.class.php',
  'member.service.MessageService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\MessageService.class.php',
  'MessageService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\MessageService.class.php',
  'member.service.NoticeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\NoticeService.class.php',
  'NoticeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\NoticeService.class.php',
  'member.service.PaymentPartnerProvider' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\PaymentPartnerProvider.class.php',
  'PaymentPartnerProvider' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\PaymentPartnerProvider.class.php',
  'member.service.RechargeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\RechargeService.class.php',
  'RechargeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\RechargeService.class.php',
  'member.service.ShareService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\ShareService.class.php',
  'ShareService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\ShareService.class.php',
  'member.service.UserService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\UserService.class.php',
  'UserService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\UserService.class.php',
  'member.service.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\FollowService.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\ImageVerificationCodeService.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\MemberServiceFactory.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\MessageService.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\NoticeService.class.php',
    5 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\PaymentPartnerProvider.class.php',
    6 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\RechargeService.class.php',
    7 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\ShareService.class.php',
    8 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\UserService.class.php',
  ),
  'member.service.interface.IFollowService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IFollowService.class.php',
  'IFollowService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IFollowService.class.php',
  'member.service.interface.IMessageService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IMessageService.class.php',
  'IMessageService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IMessageService.class.php',
  'member.service.interface.INoticeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\INoticeService.class.php',
  'INoticeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\INoticeService.class.php',
  'member.service.interface.IRechargeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IRechargeService.class.php',
  'IRechargeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IRechargeService.class.php',
  'member.service.interface.IShareService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IShareService.class.php',
  'IShareService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IShareService.class.php',
  'member.service.interface.IUserService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IUserService.class.php',
  'IUserService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IUserService.class.php',
  'member.service.interface.IVerificationCodeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IVerificationCodeService.class.php',
  'IVerificationCodeService' => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IVerificationCodeService.class.php',
  'member.service.interface.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IFollowService.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IMessageService.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\INoticeService.class.php',
    3 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IRechargeService.class.php',
    4 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IShareService.class.php',
    5 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IUserService.class.php',
    6 => 'E:\\phpWork\\lucklybet\\modules/member\\service\\interface\\IVerificationCodeService.class.php',
  ),
  'news.actions.ListAction' => 'E:\\phpWork\\lucklybet\\modules/news\\actions\\ListAction.class.php',
  'news.actions.ViewAction' => 'E:\\phpWork\\lucklybet\\modules/news\\actions\\ViewAction.class.php',
  'news.actions.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/news\\actions\\ListAction.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/news\\actions\\ViewAction.class.php',
  ),
  'news.model.News' => 'E:\\phpWork\\lucklybet\\modules/news\\model\\News.class.php',
  'News' => 'E:\\phpWork\\lucklybet\\modules/news\\model\\News.class.php',
  'news.model.NewsCategory' => 'E:\\phpWork\\lucklybet\\modules/news\\model\\NewsCategory.class.php',
  'NewsCategory' => 'E:\\phpWork\\lucklybet\\modules/news\\model\\NewsCategory.class.php',
  'news.model.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/news\\model\\News.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/news\\model\\NewsCategory.class.php',
  ),
  'news.service.NewsCategoryService' => 'E:\\phpWork\\lucklybet\\modules/news\\service\\NewsCategoryService.class.php',
  'NewsCategoryService' => 'E:\\phpWork\\lucklybet\\modules/news\\service\\NewsCategoryService.class.php',
  'news.service.NewsService' => 'E:\\phpWork\\lucklybet\\modules/news\\service\\NewsService.class.php',
  'NewsService' => 'E:\\phpWork\\lucklybet\\modules/news\\service\\NewsService.class.php',
  'news.service.NewsServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/news\\service\\NewsServiceFactory.class.php',
  'NewsServiceFactory' => 'E:\\phpWork\\lucklybet\\modules/news\\service\\NewsServiceFactory.class.php',
  'news.service.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/news\\service\\NewsCategoryService.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/news\\service\\NewsService.class.php',
    2 => 'E:\\phpWork\\lucklybet\\modules/news\\service\\NewsServiceFactory.class.php',
  ),
  'news.service.interface.INewsCategoryService' => 'E:\\phpWork\\lucklybet\\modules/news\\service\\interface\\INewsCategoryService.class.php',
  'INewsCategoryService' => 'E:\\phpWork\\lucklybet\\modules/news\\service\\interface\\INewsCategoryService.class.php',
  'news.service.interface.INewsService' => 'E:\\phpWork\\lucklybet\\modules/news\\service\\interface\\INewsService.class.php',
  'INewsService' => 'E:\\phpWork\\lucklybet\\modules/news\\service\\interface\\INewsService.class.php',
  'news.service.interface.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/news\\service\\interface\\INewsCategoryService.class.php',
    1 => 'E:\\phpWork\\lucklybet\\modules/news\\service\\interface\\INewsService.class.php',
  ),
  'test.actions.ModelAction' => 'E:\\phpWork\\lucklybet\\modules/test\\actions\\ModelAction.class.php',
  'ModelAction' => 'E:\\phpWork\\lucklybet\\modules/test\\actions\\ModelAction.class.php',
  'test.actions.*' => 
  array (
    0 => 'E:\\phpWork\\lucklybet\\modules/test\\actions\\ModelAction.class.php',
  ),
);

